GO
SET ANSI_PADDING OFF
GO
SET IDENTITY_INSERT [dbo].[TB_TIPOUSUARIO] ON
INSERT [dbo].[TB_TIPOUSUARIO] ([ID_TIPOUSUARIO], [DESCRIPCION], [ESTATUS]) VALUES (1, N'Administrador', 1)
INSERT [dbo].[TB_TIPOUSUARIO] ([ID_TIPOUSUARIO], [DESCRIPCION], [ESTATUS]) VALUES (2, N'Dominio', 1)
INSERT [dbo].[TB_TIPOUSUARIO] ([ID_TIPOUSUARIO], [DESCRIPCION], [ESTATUS]) VALUES (3, N'Grupo', 1)
INSERT [dbo].[TB_TIPOUSUARIO] ([ID_TIPOUSUARIO], [DESCRIPCION], [ESTATUS]) VALUES (4, N'Comercializadora', 1)
INSERT [dbo].[TB_TIPOUSUARIO] ([ID_TIPOUSUARIO], [DESCRIPCION], [ESTATUS]) VALUES (5, N'Agencia', 1)
INSERT [dbo].[TB_TIPOUSUARIO] ([ID_TIPOUSUARIO], [DESCRIPCION], [ESTATUS]) VALUES (6, N'Taquilla', 1)
SET IDENTITY_INSERT [dbo].[TB_TIPOUSUARIO] OFF

GO
SET ANSI_PADDING OFF
GO
SET IDENTITY_INSERT [dbo].[TB_TIPOJUEGO] ON
INSERT [dbo].[TB_TIPOJUEGO] ([ID_TIPOJUEGO], [DESCRIPCION], [PAGINA], [ESTATUS]) VALUES (1, N'Ruleta', N'ruleta.aspx', 1)
INSERT [dbo].[TB_TIPOJUEGO] ([ID_TIPOJUEGO], [DESCRIPCION], [PAGINA], [ESTATUS]) VALUES (2, N'Tripleta', N'tripleta.aspx', 1)
SET IDENTITY_INSERT [dbo].[TB_TIPOJUEGO] OFF

GO
SET ANSI_PADDING OFF
GO
SET IDENTITY_INSERT [dbo].[TB_OPCIONMENU] ON
INSERT [dbo].[TB_OPCIONMENU] ([ID_OPCIONMENU], [ID_OPCIONMENUPADRE], [NOMBRE], [DESCRIPCION], [URL], [POSICION], [ESTATUS]) VALUES (1, NULL, N'Inicio', N'Opcion 1', N'home', 1000, 1)
INSERT [dbo].[TB_OPCIONMENU] ([ID_OPCIONMENU], [ID_OPCIONMENUPADRE], [NOMBRE], [DESCRIPCION], [URL], [POSICION], [ESTATUS]) VALUES (2, NULL, N'Administración Dominios', N'Opcion 2', N'domain', 1500, 1)
INSERT [dbo].[TB_OPCIONMENU] ([ID_OPCIONMENU], [ID_OPCIONMENUPADRE], [NOMBRE], [DESCRIPCION], [URL], [POSICION], [ESTATUS]) VALUES (3, NULL, N'Administración Usuarios Internos', N'Opcion3', N'internal-users', 1600, 1)
INSERT [dbo].[TB_OPCIONMENU] ([ID_OPCIONMENU], [ID_OPCIONMENUPADRE], [NOMBRE], [DESCRIPCION], [URL], [POSICION], [ESTATUS]) VALUES (4, NULL, N'Administración Juegos', N'Opcion 4', N'games', 1900, 1)
INSERT [dbo].[TB_OPCIONMENU] ([ID_OPCIONMENU], [ID_OPCIONMENUPADRE], [NOMBRE], [DESCRIPCION], [URL], [POSICION], [ESTATUS]) VALUES (5, NULL, N'Administración Impuestos', N'Opcion 5', N'taxes', 2000, 1)
SET IDENTITY_INSERT [dbo].[TB_OPCIONMENU] OFF

GO
SET ANSI_PADDING OFF
GO
SET IDENTITY_INSERT [dbo].[TB_DIA] ON
INSERT [dbo].[TB_DIA] ([ID_DIA], [NOMBRE], [ESTATUS]) VALUES (1, N'LUNES', 1)
INSERT [dbo].[TB_DIA] ([ID_DIA], [NOMBRE], [ESTATUS]) VALUES (2, N'MARTES', 1)
INSERT [dbo].[TB_DIA] ([ID_DIA], [NOMBRE], [ESTATUS]) VALUES (3, N'MIERCOLES', 1)
INSERT [dbo].[TB_DIA] ([ID_DIA], [NOMBRE], [ESTATUS]) VALUES (4, N'JUEVES', 1)
INSERT [dbo].[TB_DIA] ([ID_DIA], [NOMBRE], [ESTATUS]) VALUES (5, N'VIERNES', 1)
INSERT [dbo].[TB_DIA] ([ID_DIA], [NOMBRE], [ESTATUS]) VALUES (6, N'SABADO', 1)
INSERT [dbo].[TB_DIA] ([ID_DIA], [NOMBRE], [ESTATUS]) VALUES (7, N'DOMINGO', 1)
SET IDENTITY_INSERT [dbo].[TB_DIA] OFF

